CREATE TABLE "students" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"First_Name"	INTEGER NOT NULL,
	"Last_Name"	TEXT NOT NULL,
	"Year"	INTEGER NOT NULL,
	"Group"	INTEGER NOT NULL,
	"Phone"	TEXT NOT NULL,
	"Email"	TEXT,
	"Mark"	NUMERIC NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "grades" (
	"ID"	INTEGER NOT NULL,
	"Grade"	NUMERIC NOT NULL,
	FOREIGN KEY("ID") REFERENCES "students"("ID") ON DELETE CASCADE
);

CREATE TABLE "professors" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"First_Name"	TEXT NOT NULL,
	"Last_Name"	TEXT NOT NULL,
	"Phone"	TEXT NOT NULL,
	"Email"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "year1" (
	"ID"	INTEGER NOT NULL,
	"Mark"	REAL NOT NULL,
	FOREIGN KEY("ID") REFERENCES "students"("ID") ON DELETE CASCADE
);

CREATE TABLE "year2" (
	"ID"	INTEGER NOT NULL,
	"Mark"	REAL NOT NULL,
	FOREIGN KEY("ID") REFERENCES "students"("ID") ON DELETE CASCADE
);

CREATE TABLE "year3" (
	"ID"	INTEGER NOT NULL,
	"Mark"	REAL NOT NULL,
	FOREIGN KEY("ID") REFERENCES "students"("ID") ON DELETE CASCADE
);

CREATE TABLE "year4" (
	"ID"	INTEGER NOT NULL,
	"Mark"	REAL NOT NULL,
	FOREIGN KEY("ID") REFERENCES "students"("ID") ON DELETE CASCADE
);

CREATE TABLE "graduates" (
	"ID"	INTEGER NOT NULL
);

